### ISSUE TITLE
cplay-ng FrameOffsetPlayer not define error

### ISSUE THREAD

**Issue by gotbletu** [xi/cplay-ng#2] opened 2015-10-03 21:23 UTC
Hey I saw your reply post, Thanks for letting me know about this fork =) , was about to give you feedback on the resuming feature but I can not even get this to start. It installed fine but just didnt start due to some errors.

$ python -V
Python 3.4.3

steps used:
$ pip install --user cplay-ng
$ cplay-ng

Traceback (most recent call last):
  File "/home/heoyea-core/.local/bin/cplay-ng", line 7, in <module>
    from cplay.cplay import main
  File "/home/heoyea-core/.local/lib/python3.4/site-packages/cplay/cplay.py", line 2178, in <module>
    exec(compile(open(rc).read(), rc, 'exec'))
  File "/etc/cplayrc", line 2, in <module>
    FrameOffsetPlayer("ogg123 -q -v -k %d %s", ".(ogg|flac|spx)$"),
NameError: name 'FrameOffsetPlayer' is not defined

**Comment by gotbletu** [comment] 2015-10-03 21:30
got it to load now

had to make a file ~/.cplayrc to override the /etc/cplayrc
but then it doesnt play any mp3s just gets more errors

$ vim ~/.cplayrc

PLAYERS = [ 
MPlayer("mplayer -vo null %s", "^http://|.(mp[123]|ogg|flac|spx|mp[cp+]|mod|xm|fm|s3m|med|col|669|it|mtm|stm|aiff|au|cdr|wav)$"),
]

**Output Error message when i play a mp3**

Traceback (most recent call last):
  File "/home/heoyea-core/.local/lib/python3.4/site-packages/cplay/cplay.py", line 2124, in main
    app.run()
  File "/home/heoyea-core/.local/lib/python3.4/site-packages/cplay/cplay.py", line 1938, in run
    self.player.backend.read_fd(self.player.backend.stderr_r)
  File "/home/heoyea-core/.local/lib/python3.4/site-packages/cplay/cplay.py", line 1441, in read_fd
    self.parse_progress()
  File "/home/heoyea-core/.local/lib/python3.4/site-packages/cplay/cplay.py", line 1435, in parse_progress
    self.parse_buf()
  File "/home/heoyea-core/.local/lib/python3.4/site-packages/cplay/cplay.py", line 1500, in parse_buf
    head = parse_time(match.group(1))
  File "/home/heoyea-core/.local/lib/python3.4/site-packages/cplay/cplay.py", line 1495, in parse_time
    l = reversed(s.split(":"))
TypeError: 'str' does not support the buffer interface

**Comment by xi** [comment] 2015-10-04 06:46
Thanks for the report!

I guess the issue is that some internals have changed. ~/.cplayrc is executed as python code within the scope of the cplay module, so it accesses interfaces that I considered private.

For now you should be able to start cplay-ng with a completely empty cplayrc.

As a general fix I see 3 options:
1.  Remove cplayrc support completly
2.  Disable cplayrc support and allow to enable via command line flag. Add a warning to the docs that internal APIs have changed.
3.  Wrap the execution of cplayrc in a `try…catch` and log a warning on failure.

@gotbletu: What do you think?

**Comment by gotbletu** [comment] 2015-10-04 08:28
I have never really needed to use any config files for [cplay](https://aur.archlinux.org/packages/cplay-git/) or [play.py](https://aur.archlinux.org/packages/play-git/) fork. I think the play.py fork has disable cplayrc and just allow commandline flags. So that would be my pick also

**Comment by xi** [comment] 2015-10-04 08:44
I noticed that there is a second issue related to bytestrings in python3 in your second message. It should be fixed now (226e73df11941c434ea57125c0e47ae12b9ebfae).

Could you please verify so this issue can be closed?

> $ pip install --user cplay-ng

Note that in order to test the feature from #1 you need to checkout that branch:

```
git clone https://github.com/xi/cplay-ng.git
cd cplay-ng
git fetch origin feature-recover
git checkout feature-recover
python cplay/cplay.py
```

**Comment by gotbletu** [comment] 2015-10-05 01:06
Still got the same error message. I'll test issue #1 next and let you know

**Comment by xi** [comment] 2015-10-05 08:48
> Still got the same error message.

Was this with the version from git master or from pip? The fix is not published to pip yet.

**Comment by gotbletu** [comment] 2015-10-05 10:20
was from the pip version

**Comment by xi** [comment] 2015-12-17 10:42
@gotbletu The fixed version has been published to pip in the meantime. Can you please verify that this issue is fixed?

**Comment by xi** [comment] 2016-01-07 12:23
I assume this has been fixed now.

**Closed as completed by xi** 2016-01-07 12:23 UTC
